# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**\*.sln'
    feedsToUse: 'select'
  displayName: Nuget Restore
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    clean: false
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/bin/OscNet
    artifact: OscNet